# Generated by Django 3.1.1 on 2020-09-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='img',
            new_name='image',
        ),
    ]
