# Generated by Django 3.1.1 on 2020-09-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20200922_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
